export const initCenterList = [{
		id: 1,
		img: "/static/images/pic_1.jpg",
		title: "去有你的地方",
		type: "短剧",
		price: "80.00",
	},
	{
		id: 2,
		img: "/static/images/pic_1.jpg",
		title: "隐秘而伟大",
		type: "短剧",
		price: "90.00",
	},
	{
		id: 3,
		img: "/static/images/pic_1.jpg",
		title: "巨富归来",
		type: "短剧",
		price: "85.00",
	}
]

export const initBottomList = [{
		id: 1,
		img: "/static/images/pic_2.jpg",
		title: "父爱如山",
		type: "短剧",
		price: "85.00",
		left: 583,
		used: 17,
	},
	{
		id: 2,
		img: "/static/images/pic_2.jpg",
		title: "后会有期",
		type: "短剧",
		price: "75.00",
		left: 544,
		used: 16,
	},
	{
		id: 3,
		img: "/static/images/pic_2.jpg",
		title: "西游记",
		type: "电视剧",
		price: "80.00",
		left: 370,
		used: 15,
	},
	{
		id: 4,
		img: "/static/images/pic_2.jpg",
		title: "狂飙",
		type: "电视剧",
		price: "85.00",
		left: 523,
		used: 12,
	},
	{
		id: 5,
		img: "/static/images/pic_2.jpg",
		title: "漫长的季节",
		type: "电视剧",
		price: "85.00",
		left: 583,
		used: 17,
	},
	{
		id: 6,
		img: "/static/images/pic_2.jpg",
		title: "猎冰",
		type: "电视剧",
		price: "85.00",
		left: 583,
		used: 17,
	},
	{
		id: 7,
		img: "/static/images/pic_2.jpg",
		title: "繁花",
		type: "电视剧",
		price: "85.00",
		left: 583,
		used: 17,
	},
	{
		id: 8,
		img: "/static/images/pic_2.jpg",
		title: "汉武大帝",
		type: "电视剧",
		price: "85.00",
		left: 583,
		used: 17,
	}
]